version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: course         
      POSTGRES_USER: postgre          
      POSTGRES_PASSWORD: root    
    ports:
      - "5432:5432" 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin            
    ports:
      - "8080:80"  
    depends_on:
      - db 